# Generated by Django 5.1.2 on 2025-10-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortFolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project-images/')),
                ('title', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=255)),
                ('skills', models.JSONField(default=list)),
                ('live_demo', models.URLField(blank=True, null=True)),
                ('code_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Projects',
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
